server:
  port: 8080
spring:
  application:
    name: ticketing-project-rest
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/cyber
    username: postgres
    password: 12345678994j
    driver-class-name: org.postgresql.Driver
  #  initialization-mode: always
    data: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enabled: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: cybertekschool.email@gmail.com
    password: Cybertekschool@2020
security:
  jwt:
    secret-key: cyber
springdoc:
  swagger-ui:
    path: /swagger-ui.html